### ISSUE TITLE
Build fails with npm@4.1.1 and node@v7.4.0

### ISSUE THREAD

**Issue by cioccarellia** [cSploit/client#2]
I've tried to build the client app with `npm run build` but I get this error message:
```
andrea$ npm run build

> app@1.0.0 build /Users/andrea/Desktop/client-master/app
> node build/build.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/andrea/Desktop/client-master/app/build/check-versions.js:1:76)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! app@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls app
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrea/Desktop/client-master/app/npm-debug.log
```

Debug log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@4.1.1
3 info using node@v7.4.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle app@1.0.0~prebuild: app@1.0.0
6 silly lifecycle app@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle app@1.0.0~build: app@1.0.0
8 verbose lifecycle app@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle app@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/andrea/Desktop/client-master/app/node_modules/.bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle app@1.0.0~build: CWD: /Users/andrea/Desktop/client-master/app
11 silly lifecycle app@1.0.0~build: Args: [ '-c', 'node build/build.js' ]
12 silly lifecycle app@1.0.0~build: Returned: code: 1  signal: null
13 info lifecycle app@1.0.0~build: Failed to exec build script
14 verbose stack Error: app@1.0.0 build: `node build/build.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid app@1.0.0
16 verbose cwd /Users/andrea/Desktop/client-master/app
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.4.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error app@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the app@1.0.0 build script 'node build/build.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the app package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/build.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs app
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls app
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Rubenoo** [comment]
Have you done "npm install" before running "npm run build"?  If not I suggest you do it. If it doesn't solve the problem you need some help from @Silur

**Comment by Silur** [comment]
My first thought was `npm install` too, let me know whether it still doesn't work

**Comment by cioccarellia** [comment]
Yes, I'll try it as soon as possible

**Comment by cioccarellia** [comment]
Sorry for the stupid error: Now I can build app and launch it. Great job!
